import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export const config = { map: true };

const Home: NextPage = () => {
  let [transform3d, setTransform3d] = useState({
    transform: "translate3d(0, 0, 0px)",
  });
  async function transform(screenX: number, screenY: number) {
    let x, y;
    let Width = window.innerWidth / 2;
    let Height = window.innerHeight / 2;
    x = ((Width - screenX) / 20).toFixed(1);
    y = ((Height - screenY) / 20).toFixed(1);
    await setTransform3d({
      transform: `translate3d(${x}px, ${y}px, 0px)`,
    });
  }
  function handleMouseMove(e: any) {
    window.requestAnimationFrame(() => {
      transform(e.screenX, e.screenY);
    });
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Growth Diary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.Cover} onMouseMove={handleMouseMove}>
          <div className={styles.image} style={transform3d}>
            <div className={styles.img}>
              <Image
                src="http://g.auroraone.top/1594348066004.png"
                layout="fill"
                sizes="100vh"
                quality={100}
                objectFit="cover"
                alt=""
              />
            </div>
          </div>
          <div className={styles.mask}></div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="#" rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
