import type { NextPage } from "next";
import {useState} from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Home: NextPage = () => {

  let [transform, setTransform] = useState({
    transform:''
  // transform: translate3d(0,0,0) rotate(0.001deg);
  //   const startStyle = {transform:`rotate(${this.state.rotate}deg)`};
  })
  const startStyle = (x:number=0,y:number=0) => {
    return setTransform({transform:`translate3d(${x+10}px,${y+10}px,0px) rotate(0.001deg)`})
  }
    function handleMouseMove(e: any) {
      console.log(e.screenX,e.screenY);
      // window.requestAnimationFrame(handleMouseMove)
      startStyle(e.screenX,e.screenY)
    }
  return (
    <div className={styles.container}>
      <Head>
        <title>Growth Diary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.Cover} style={transform} >
          <div className={styles.image}>
          <Image
            src="http://g.auroraone.top/1594348066004.png"
            layout="fill"
            sizes="100vh"
            objectFit="cover"
            alt=""
            onMouseMove={handleMouseMove}
          />
          </div>
          <div className={styles.mask}></div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="#" rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
